name: saturn_flutter
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  flutter_staggered_grid_view: ^0.4.1
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  dotted_border: 2.0.0+1
  permission_handler: ^10.0.0
  graphql_flutter: ^5.1.0
  http: ^0.13.5
  flutter_launcher_icons: ^0.10.0
  sizer: ^2.0.15
  url_launcher: ^6.1.6
#  persistent_bottom_nav_bar: ^5.0.2
  razorpay_flutter: ^1.1.1
  intl:
  lottie: ^1.4.3
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/images/app_icon.png"
flutter_native_splash:
  background_image: assets/images/splash_screen.png
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
